- alias: 'Turn on / off lights at 0400'
  trigger:
    platform: time
    at: '04:00'
  action:
    - delay: '00:{{ (range(1, 15)|random|int) }}:00'
    - service: homeassistant.turn_on
      entity_id: switch.family_room_light
    - delay:
        minutes: 20
    - service: homeassistant.turn_off
      entity_id: switch.family_room_light

- alias: 'Good Night - Lights Out'
  trigger:
    platform: time
    at: '02:00'
  action:
    - delay: '00:{{ (range(1, 20)|random|int) }}:00'
    - service: homeassistant.turn_off
      entity_id: switch.family_room_light

- alias: 'Light on at sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-01:10:00"
  action:
    - delay: '00:{{ (range(10, 45)|random|int) }}:00'
    - service: homeassistant.turn_on
      entity_id: switch.family_room_light

- alias: 'Its sunrise, turn off the lights'
  trigger:
    platform: sun
    event: sunrise
    offset: '00:00:00'
  action:
    - delay: '00:{{ (range(10, 45)|random|int) }}:00'
    - service: homeassistant.turn_off
      entity_id: switch.family_room_light

- alias: 'Test'
  trigger:
    platform: time
    at: '20:30'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.family_room_light
    - delay:
        minutes: 2
    - service: homeassistant.turn_on
      entity_id: switch.family_room_light












