title: My Awesome Home
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
  
resources:
  - url: /local/custom-lovelace/alarm_control_panel-card/alarm_control_panel-card.js?v=2
    type: js  

views:
    # View tab title.
  - title: Example
    # Optional unique id for direct access /lovelace/${id}
    id: example
    # Each view can have a different theme applied.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.galaxys7
          - device_tracker.galaxys9
        state_filter:
          - 'home'
        card:
          type: glance
          title: People that are home

        # The picture entity card will represent an entity with a picture
      - type: picture-entity
        image: https://www.home-assistant.io/images/default-social.png
        entity: switch.sonoff_extension_cord

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Lights
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - switch.sonoff_extension_cord
          - entity: switch.family_room_light
            name: Family Room Lights
            

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
          
      - type: custom:alarm_control_panel-card
        entity: alarm_control_panel.home
        show_keypad: true
        title: My Alarm
        style: '--alarm-color-disarmed: var(--label-badge-blue);'
        states:
          - arm_home
          - arm_away